- name: Install Python 3.9 and Maven on webserver
  hosts: webserver
  gather_facts: false
  become: true

  tasks:
    - name: Install python3.9
      yum:
        name: python3.9
        state: present

    - name: Install python3-pip
      yum:
        name: python3-pip
        state: present

    - name: Install maven
      yum:
        name: maven
        state: present

    - name: Create a test file
      file:
        path: /tmp/ansible.txt
        state: touch
